# custom agent is simply A LOT faster at building than the hosted queue
# (esp. since nuget packages can be cached) but you can also use hosted queue
# with no problems as I am not using any custom software during build

resources:
- repo: self
  clean: true
trigger:
  batch: true
  branches:
    include:
    - master
pool:
  name: Default
variables:
  BuildConfiguration: 'release'
  Major: '1'
  Minor: '0'
  Patch: '0'
name: $(Major).$(Minor).$(Patch).$(BuildID)
steps:
- checkout: self
  submodules: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Infrastructure Scripts'
  inputs:
    PathtoPublish: deploy
    ArtifactName: deploy


- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(Major).$(Minor) /p:FileVersion=$(Build.BuildNumber)'


- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish

    publishWebProjects: false
    projects: HostMerger/HostMerger.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) /p:Version=$(Major).$(Minor) /p:FileVersion=$(Build.BuildNumber)'
    zipAfterPublish: false


- task: PublishBuildArtifacts@1
  displayName: 'Publish build Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: app
