name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: build
      run: dotnet build -c Release

    - name: test
      run: dotnet test -c Release --no-build **/*.Test*.csproj

    - name: publish
      run: dotnet publish -c Release **/HostMerger.csproj
      
    - uses: actions/upload-artifact@master
      with:
        name: function
        path: HostMerger/bin/Release/netcoreapp3.1/publish
      
  release:
    needs: build
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@master
      with:
        name: function
        path: drop
        
    - name: list
      run: ls drop
